version: "3.9"

services:
  data-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-data-scheduler
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m src.data.scheduler
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
